### ISSUE TITLE
Input handling doesn't make use of modern SDL2 controller handling

### ISSUE THREAD

**Issue by DanTheMan827** [djyt/cannonball#77] opened 2021-03-19 14:47 UTC
SDL2 has two ways to handle input from gamepads, the controller interface and the joypad interface, when reading joypad buttons, you get the raw button index from the controller, when reading the controller interface you get an abstracted button index mapped according to the gamecontrollerdb.txt file

The result of not using the controller interface is that the gamecontrollerdb.txt is effectively ignored and it uses the raw indexes.

Here's the SDL2 platform implementation for OpenLara to better show what I mean https://github.com/XProger/OpenLara/blob/master/src/platform/sdl2/main.cpp#L364

As you can see, it handles both controllers and joypads, this is because if there's no mapping for the controller, it will still be usable as a joypad.

**Comment by djyt** [comment] 2021-03-19 15:07
Can you take a look at the changes I made to input.cpp earlier. I'm hoping that this automatically sets up sensible controls using gamecontrollerdb.txt. The mapping I created in void Input::open_joy() appears to setup my controller ok and map the buttons correctly automatically.

**Comment by DanTheMan827** [comment] 2021-03-19 19:36
Oh, I didn't see those commits, my issue was based on the code as of last night...

I'll give that a shot, but it seems like that may work since you grab the button index on joy connect if it's a gamepad.

But do you use the logical index for the bindings, or do you save the actual index?

**Comment by DanTheMan827** [comment] 2021-03-19 22:45
FYI, I did test the commits you made, and they don't seem to have made any difference, the mappings are still different between controllers.

**Comment by djyt** [comment] 2021-03-20 17:38
I find the fact this doesn't work for you a bit baffling. If I don't setup ANY mappings at all for my 360 controller (e.g. I use the default config.xml file where everything is set to '-1'), the code I've written correctly assigns everything perfectly - all analog and digital controls. Whilst I can imagine that for some controllers the mappings would seem sub-par, I don't understand why they wouldn't work full-stop. I haven't coded anything that's 360 specific after all. I just detect it as a game controller and then request the controls to be assigned to sensible buttons. 

Short of actually getting a different controller, I'm going to struggle to guess how to fix this further. Can you set some break points in the code and figure out how it's going wrong for you? Can you send me details of which buttons on your controller the CannonBall controls get assigned to?

**Comment by djyt** [comment] 2021-03-20 17:42
I suspect you may have mis-interpreted my code.

Just to clarify it works as follows:

1/ If the controller is not configured at all (buttons/axis set to -1 in config.xml) it will attempt to assign the axis and buttons automatically to something sensible (e.g. accelerate is right trigger, brake is left trigger, start is start etc.)

2/ Once configured, this process will never take place again. So swapping a new different controller in wouldn't trigger a reconfiguration. I can add a "reset controls to default" option in the menu, but no point if this isn't even working in the first place.

3/ The automatically assigned controls can be remapped through the in-built configuration menu. So buttons and axis can be reassigned by the user.

4/ Everything works perfectly for me. Argh. :-D

**Comment by DanTheMan827** [comment] 2021-03-20 19:54
"It works fine on my machine" 😂 

The proper way for handling the mapping would be to store the _controller_ button number (not joypad) in the config and compare the input given by the game controller events (again, not the joypad events) to the ones assigned in the config file.

This way it wouldn't matter if you changed controllers or not, all pads would have the same controller button indexes for the buttons based on their physical position on the pad (SDL2 is based around a 360 layout)

So if you checked for a controller button of Y, it would also give you that value with a PS3 controller, even if you swapped controllers with the game running.

**Comment by djyt** [comment] 2021-03-21 16:11
I think you're just reiterating what I wrote in point 2 with regard to storing in the config.xml? 

What I'm trying to get to the bottom of is whether it works for other controllers. Can you confirm whether your controller is working? 

I've gone through the implementation line by line in the debugger and all seems in order. 

If it is working, then I can go and finish the implementation and close this bug.

**Comment by DanTheMan827** [comment] 2021-03-21 17:00
Yeah, I knew you were joking with 4

I'm not saying your code doesn't work, I'm just saying that it doesn't work as one would expect if you switch controllers.

Regarding point 2, since it auto-configures to one controller you can't then swap controllers and expect the proper mapping afterwards, your code would work and give the appropriate mappings one-time, but it you use the controller method like in #80, you can use any controller and switch them out even after the first time.

With your code as you describe it, I can't plug in a 360 controller, play the game, and then swap in for a PS3 controller (or any other really) without then manually re-mapping the controls, but with the controller interface, the controller wouldn't matter since the buttons and axes are in a [standardized form](https://wiki.libsdl.org/SDL_GameControllerButton) that doesn't change from controller to controller, it's just an abstraction that SDL2 provides to make things easier.

there's the joystick and gamecontroller methods to read the pad, but it doesn't really make a whole lot of sense to use gamecontroller just to get raw button values for joystick when you could just use gamecontroller to read the values in the first place.

**Comment by djyt** [comment] 2021-03-21 17:14
Awesome, thanks for the information and help on this.

I'll take a look at the pull request in the coming days. As you say, this may well be a better solution.

**Comment by djyt** [comment] 2021-03-21 18:12
Merged #80 in - looks good. 

I'll leave this open until I fix the use-case of plugging a new controller in.

**Comment by djyt** [comment] 2021-03-21 18:33
Hmm no sadly on further inspection #80 created two problems for me:
- Analog controls appeared to be 'stuck' on, once pulled the accelerator remained active.
- Redefining the analog controls no longer worked. 

I will go back and review at a later date, but I've reverted as it left the codebase in a non-working state.

**Comment by DanTheMan827** [comment] 2021-03-21 19:44
That’s weird, I didn’t try remapping the analog, but I did test with a 360 controller on Ubuntu 18.04 and it worked fine for analog controls

hopefully this is still useful though

**Comment by djyt** [comment] 2021-03-22 09:47
Yes, I'll investigate a little further at some point. 

It's another damn example of "works for me" - I couldn't see anything wrong with your code by eyeballing it (I didn't have time to go through with a debugger to track down the cause), but it unfortunately didn't work for me out of the box at least. 🙃

**Comment by djyt** [comment] 2021-03-23 14:16
I had a short amount of time to look into this. Your implementation was pretty much there, but I made the following changes, which you can review in commit **711bbe7 - Improved Support for SDL 2 Controllers.**

1/ The values returned by analog trigger buttons differs between the SDL Joystick and SDL Controller implementations. 
- **Controllers:** Trigger axis values range from 0 to SDL_JOYSTICK_AXIS_MAX (32767)
- **Joysticks:** All axis range from -32768 to 32767 (I am unsure if this is consistent between joysticks, probably not)

With the XBox 360 pad, the trigger values returned are different depending on whether it's initialized as a controller or joystick. I guess this is to be expected, as the SDL controller class is designed to normalise input behaviour. 

This caused the analog controls to get 'stuck' on in your initial implementation with the 360 pad. I now detect between joystick and controller and scale those inputs appropriately. I assume that all controllers fall between the range specified above. I assume all joystick trigger buttons use the alternate range. The latter of these two assumptions could be incorrect and I would need to test on a wider range of non-controller joysticks. 

2/ I made a minor change to avoid capturing controller insert/removal events as this caused the initialization code to be called twice. All controllers are caught by the joypad event.

**Comment by djyt** [comment] 2021-03-23 16:39
Thanks, yep I spotted that (and changed it) shortly after writing to you.

It doesn't seem to impact anything, but I'd agree it's bad practice to leave it like that! :)

**Closed by djyt** 2021-03-23 16:39 UTC
